### ISSUE TITLE
Only one section open at a time?

### ISSUE THREAD

**Issue by daviddelmonte** [rob-nash/CollapsibleTable#1]
Rob, thanks for this control. Would it be possible to close other sections when one is opened? How could I go about this? Thanks!

**Comment by rob-nash** [comment]
I have been meaning to add that feature. I might take a look this weekend.

If you need this feature quickly, you might want to use this version (objective-c) https://github.com/rob-nash/CollapsableTable

**Comment by daviddelmonte** [comment]
Thanks Rob, I hope you are able to crack a Swifty version. If not, the ObjC version will suffice. I appreciate your code!

**Comment by rob-nash** [comment]
I have a prototype in the develop branch but the animations aren't quite there yet.

**Comment by daviddelmonte** [comment]
Apologies for very late reply.... travel and small surgery. Anyway, thanks for the mod. it's just what I needed. I really appreciate it.

David
